import type { NextPage } from 'next'
import Head from 'next/head'
import {useState} from 'react'
import Nftview from '../components/Nftview.jsx'
import Wallet from '../components/Wallet.jsx'


const Home: NextPage = () => {
  const [address,SetAddress]=useState<string>('')
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {address ? <Nftview address={address}/> : <Wallet setAddress={SetAddress}/>}
    </>
  )
}


export default Home
