import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from 'react'
import Nftview from '../components/Nftview'
import { useRouter } from 'next/router'


const Home: NextPage = () => {
  const [address,SetAddress]=useState('')
  const connectWallet=async()=>{
    console.log("Requesting account...")

    if(window.ethereum){
      console.log('detected')
      try {
        const accounts=await window.ethereum.request({
          method:"eth_requestAccounts"
        });
        console.log(accounts)
        SetAddress(accounts[0])
      }catch(err){
        console.log(error)
      }
    }else{
      console.log('Connect your wallet')
    }
  } 
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello Web3!
      <button onClick={connectWallet}>Connect your Ethereum Wallet</button>
      {address && <Nftview/>}
    </div>
  )
}

export default Home
